Please read the following instructions: 
- Lab notebooks will be graded. 
- All tasks must be completed, following the instruction, to achieve a full mark. 
- Part marks will not be provided.
- Remember to Execute and Save each cell. 
- Submit the .pdf format of saved cells (File->Download as) via Blackboard before the deadline of each lab. 
- Submissions other than .pdf will be graded as 0.
- Name the submission file as: Firstname_Lastname_LX_Y where Firstname is your first name, last name is your last name, X is the lab number, and Y is the initial of lecture day. For example, Lab 4 submission for John Smith who attends the Mondays lectures is: John_Smith_L4_M.pdf  
- Submissions not following the above nameing format will be graded as 0.


# Lab 2 - NumPy



##### First Import NumPy as np

In [31]:
#Write your code here
import numpy as np

##### Write a code to show array of 5 zeros 

In [32]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


##### Write a code to show an array of 5 ones

In [33]:
#Write your code here
print(np.ones(5))

[1. 1. 1. 1. 1.]


##### Write a code to show integer numbers from 0 to 20

In [34]:
print(np.arange(20))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


##### Write a code to show integer numbers from 0 to 20 with step 3

In [35]:
print(np.arange(0, 20, 3))

[ 0  3  6  9 12 15 18]


##### Write a code to show integer numbers from -50 to 20 with step 5

In [36]:
print(np.arange(-50, 20, 5))

[-50 -45 -40 -35 -30 -25 -20 -15 -10  -5   0   5  10  15]


##### Write a code to show the max number in a randomly (float numbers between 0,1 from a uniform distribution) generated numpy array of size 5x6.

In [37]:
randomArray = np.random.rand(5, 6)
print(randomArray)
print(np.max(randomArray))

[[0.53902536 0.92876829 0.79822251 0.7762159  0.07659598 0.83534498]
 [0.03614778 0.63378507 0.38754472 0.73941739 0.59402228 0.08563103]
 [0.34119142 0.28024076 0.78796995 0.67386637 0.06469487 0.98442038]
 [0.24396737 0.4973332  0.13500647 0.90110646 0.82177457 0.84184222]
 [0.48432992 0.63491682 0.3863979  0.07118283 0.30577604 0.86248417]]
0.984420381177984


##### Write a code to show a 4x6 matrix with values ranging from 0 to 24

In [38]:
print(np.arange(0, 24).reshape(4, 6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


##### Write a code to show a 3x3 identity matrix

In [39]:
print(np.eye(3, 3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#####  Write a code to show a random number between 0 and 10

In [40]:
# 0 excluded
print(np.random.randint(1, 10))
# 0 inclusive
print(np.random.randint(10))

7
2


##### Write a code to Create the following matrix:

In [41]:
print(np.arange(0, 1, 0.01))

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]


Run the array below and answer the questions.

In [42]:
array = np.arange(0,25).reshape(5,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
#Write a code to create this output
array[3]

array([15, 16, 17, 18, 19])

In [44]:
#Write a code to create this output from the previous array
print(array[3, 4])

19


In [45]:
#Write a code to create this output
array[3:5]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])