# NumPy 



## Numpy Features:
    * Typed multidimentional arrays (matrices)
    * Fast numerical computations (matrix math)
    * High-level math functions 


## Why do we need NumPy?
    * Python does numerical computations slowly.
    * 1000 x 1000 matrix multiply
    * Python triple loop takes > 10 min.
    * Numpy takes ~0.03 seconds


## NumPy Overview:
    * Arrays
    * Shaping and transposition
    * Mathematical Operations
    * Indexing and slicing
    * Broadcasting


## How to use  NumPy

After complete the installation you can import it as a library:

In [1]:
import numpy as np



# Arrays

* vectors, matrices, and tensors

## Creating NumPy Arrays



In [2]:
x = [1,2,3]
x
print(type(x))

<class 'list'>


In [3]:
xx = np.array(x)
print(type(xx))

<class 'numpy.ndarray'>


In [4]:
x = list(range(0,10))
print(x)
print(type(x))
print(len(x))


x = np.arange(10)
print(x)
print(type(x))
print(x.shape)
print(x.dtype)
print(x.ndim)

x = np.zeros((4,5,6,3))
print(x.ndim)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>
10
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)
int64
1
4


In [5]:
x = np.arange(3,10,2)
print(x)
print(x.shape)
print(x.ndim)

[3 5 7 9]
(4,)
1


In [6]:
x = np.zeros((4,3))
print(x)
print(x.ndim)
print(x.shape)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2
(4, 3)


In [7]:
x = np.zeros((4,3,2))
print(x)
print(x.ndim)
print(x.shape)


[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
3
(4, 3, 2)


In [8]:
y = [1,2,3]
print(type(y))
y = np.array(y)
print(y)

<class 'list'>
[1 2 3]


In [9]:
y = [[1,2,3],[4,5,6],[7,8,9]]
print(type(y))
print(np.array(y))

<class 'list'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
y = [[1,2,3],[4,5,6],[7,8,9,10]]
print(type(y))
print(np.array(y))

<class 'list'>
[list([1, 2, 3]) list([4, 5, 6]) list([7, 8, 9, 10])]


/var/folders/yn/_50lh29d3b30g7y82_6f3ysh0000gn/T/ipykernel_3772/1939650120.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print(np.array(y))


In [11]:
a = np.random.random((3,4,5))
print(a)

[[[0.2171446  0.72326766 0.30341471 0.11261543 0.5136638 ]
  [0.91431858 0.82428642 0.68478585 0.25754839 0.89987411]
  [0.76839625 0.54050134 0.53035906 0.00301855 0.79819338]
  [0.94539973 0.76189871 0.63864902 0.03061361 0.69724722]]

 [[0.22200036 0.56448937 0.68421935 0.96809699 0.46427289]
  [0.96720819 0.21050194 0.89714724 0.9609868  0.50226159]
  [0.77892883 0.58401654 0.47244098 0.02446586 0.79695734]
  [0.9740101  0.88939397 0.82762892 0.69134924 0.69168398]]

 [[0.33037926 0.06560622 0.96928419 0.56733015 0.77283187]
  [0.10057528 0.19848023 0.20025191 0.42415614 0.25925063]
  [0.91405949 0.31477921 0.02877681 0.25727695 0.64114503]
  [0.71622618 0.90852749 0.96570921 0.19479386 0.0752091 ]]]


In [12]:
a = np.random.randint(0, 10, (3,3))
print(a)

[[3 1 8]
 [5 9 0]
 [7 2 0]]


In [13]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
a = np.random.random((3,4))
print(a)

[[0.48751565 0.69532429 0.94642409 0.29929238]
 [0.90974592 0.80381553 0.28984206 0.97858371]
 [0.67737577 0.60324064 0.97475719 0.68605427]]


In [15]:
b = np.random.random((3,4))
print(b)

[[0.81992286 0.74261326 0.89638443 0.04299554]
 [0.33833515 0.52084861 0.07813744 0.94888524]
 [0.90489089 0.16590985 0.418673   0.74268175]]


In [16]:
print(b*a)

[[0.39972522 0.51635704 0.84835982 0.01286824]
 [0.30779902 0.4186662  0.02264752 0.92856363]
 [0.61295116 0.10008356 0.40810452 0.50951999]]


In [17]:
print(b-a)

[[ 0.33240721  0.04728897 -0.05003967 -0.25629684]
 [-0.57141077 -0.28296692 -0.21170462 -0.02969847]
 [ 0.22751513 -0.4373308  -0.55608418  0.05662749]]


In [18]:
print(20*b-a)

[[15.9109415  14.15694098 16.98126442  0.56061841]
 [ 5.85695708  9.61315667  1.27290674 17.999121  ]
 [17.42044212  2.71495628  7.39870287 14.16758083]]


In [19]:
b1 = b**2
b2 = b*b
print('b1 is:',b1)
print(30*'*')
print('b2 is:',b2)

print(b1==b2)
print(b1-b2)
print(np.sum(b1-b2))

if np.sum(b1-b2)==0:
    print('b1 is equal to b2.')


b1 is: [[0.67227349 0.55147446 0.80350504 0.00184862]
 [0.11447067 0.27128327 0.00610546 0.90038319]
 [0.81882753 0.02752608 0.17528708 0.55157619]]
******************************
b2 is: [[0.67227349 0.55147446 0.80350504 0.00184862]
 [0.11447067 0.27128327 0.00610546 0.90038319]
 [0.81882753 0.02752608 0.17528708 0.55157619]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
0.0
b1 is equal to b2.


## Methods to generate Arrays

There are lots of built-in ways to generate Arrays

### arange

NumPy arange() is one of the array creation routines based on numerical ranges. It creates an instance of ndarray with evenly spaced values and returns the reference to it. You can define the interval of the values contained in an array, space between them, and their type with four parameters of arange()

In [20]:
np.arange(start=1, stop=10, step=3)

array([1, 4, 7])

In [21]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [22]:
np.arange(0,6,2)

array([0, 2, 4])

#### Providing Negative Arguments


In [23]:
np.arange(-5, 6, 4)

array([-5, -1,  3])

In [24]:
#Example:
np.arange(0, 1, 0.2)


array([0. , 0.2, 0.4, 0.6, 0.8])

In [25]:
#Example:
np.arange(7, 0, -3)

array([7, 4, 1])

### zeros and ones in Numpy

The zeros() function is used to get a new array of given shape and type, filled with zeros.

In [26]:
np.zeros(3)

array([0., 0., 0.])

In [27]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
np.ones(3)

array([1., 1., 1.])

In [29]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace in Numpy
Return evenly spaced numbers over a specified interval.

In [30]:
np.linspace(0,20,3)

array([ 0., 10., 20.])

In [31]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## np.eye in Numpy
Return a 2-D array with ones on the diagonal and zeros elsewhere.



In [32]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Random Numbers in Numpy

random() method returns a random float number between 0.0 to 1.0. The function doesn't need any arguments.

### rand
rand() function creates an array of specified shape and fills it with random values.

What is the difference between Rand and randn in Numpy?


* randn generates samples from the normal distribution, while 
* numpy. random. rand from a uniform distribution (in the range [0,1)).

np.random.rand(5)

In [33]:
np.random.rand(4,3)

array([[0.55536832, 0.68704941, 0.7430948 ],
       [0.15389064, 0.38500854, 0.74606438],
       [0.42208686, 0.71294639, 0.97705707],
       [0.97703308, 0.38142922, 0.05773199]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [34]:
np.random.randn(2)

array([1.09222155, 1.51129473])

In [35]:
np.random.randn(5,5)

array([[-0.85746224, -0.62696738,  1.19571964,  0.54079219, -0.36717396],
       [-0.35049501, -1.51741334, -0.24462241,  0.47029341,  1.21659583],
       [ 0.5217255 ,  0.34337831,  0.32126579, -0.44047989, -0.17445546],
       [-0.201569  ,  0.53964593, -1.63351843,  0.02475565,  0.15084518],
       [-1.0022767 , -0.5474942 , -1.05435151,  0.32477477, -0.53780669]])

In [36]:
np.random.random((5,5))

array([[0.36146729, 0.70804122, 0.20043795, 0.64846685, 0.12599898],
       [0.56074144, 0.64610675, 0.89435042, 0.29025195, 0.70680666],
       [0.84796848, 0.68014573, 0.65319517, 0.11035324, 0.30844983],
       [0.6026325 , 0.70518886, 0.22030322, 0.30669936, 0.81558815],
       [0.45575172, 0.67973435, 0.56590656, 0.14005806, 0.75935794]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [37]:
np.random.randint(1,100)

44

In [38]:
np.random.randint(1,100,10)

array([71, 86, 21, 12, 13, 97,  7, 54, 33, 48])



Let's discuss some useful attributes and methods or an array:

#### Reshape
reshape() function shapes an array without changing the data of the array.

In [39]:
a = np.random.random((3,4))
print(a)
print(a.shape)

[[0.5844003  0.12822887 0.71837095 0.29963697]
 [0.9067024  0.74329524 0.77161414 0.80667884]
 [0.26660204 0.52785243 0.01030299 0.24411087]]
(3, 4)


In [40]:
b = np.reshape(a,(1,12))
print(b)
print(b.shape)
b = np.reshape(a,(6,2))
print(b)
print(b.shape)
b = np.reshape(a,(4,3))
print(b)
print(b.shape)

[[0.5844003  0.12822887 0.71837095 0.29963697 0.9067024  0.74329524
  0.77161414 0.80667884 0.26660204 0.52785243 0.01030299 0.24411087]]
(1, 12)
[[0.5844003  0.12822887]
 [0.71837095 0.29963697]
 [0.9067024  0.74329524]
 [0.77161414 0.80667884]
 [0.26660204 0.52785243]
 [0.01030299 0.24411087]]
(6, 2)
[[0.5844003  0.12822887 0.71837095]
 [0.29963697 0.9067024  0.74329524]
 [0.77161414 0.80667884 0.26660204]
 [0.52785243 0.01030299 0.24411087]]
(4, 3)


In [41]:
b = np.arange(24)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [42]:
b.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

### max,min

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [43]:
a = np.random.random((3,4))
print(a)

[[0.34868834 0.07108238 0.4009814  0.12779434]
 [0.49254932 0.116297   0.305853   0.59777311]
 [0.04649759 0.6214867  0.19026041 0.9828098 ]]


In [44]:
print(np.sum(a))
print(np.min(a),a.min())
print(np.max(a),a.max())
print(np.mean(a),a.mean())

4.302073382431795
0.04649759240605533 0.04649759240605533
0.9828097951563801 0.9828097951563801
0.3585061152026496 0.3585061152026496


In [45]:
c

NameError: name 'c' is not defined

In [ ]:
c.max()

In [ ]:
c.min()

In [ ]:
a = np.random.random((3,4))
print(a)

In [ ]:
b = a[1,1:3]
print(b)

In [ ]:
a[1,1] = 2+a[1,1]
print(a)

In [ ]:
a[1,1] *= 2
print(a)

In [ ]:
print(a)

In [ ]:
c = a[:,-1]
print(c)

In [ ]:
print(a)

In [ ]:
print(a>0.5)

In [ ]:
# How many numbers in the variable 'a' are more than 0.5?

In [ ]:
print(np.sum(a>0.5))

## Shape

shape is a tuple that always gives dimensions of the array. The shape function is a tuple that gives you an arrangement of the number of dimensions in the array. If Y has w rows and z columns, then Y. shape is (w,z)

In [ ]:
# Vector
b.shape

# What is NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [ ]:
import numpy as np

In [ ]:
#Creating sample array
x = np.arange(0,10,5)

In [ ]:
#Show
x

The simplest way to pick one or some elements of an array looks very similar to python lists:

* Get a value at an index with Bracket

In [ ]:
x[4]

* Get values in a range

In [ ]:
x[2:5]

## Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.
Broadcasting Rules:
* If the arrays don't have the same rank then prepend the shape of the lower rank array with 1s until both shapes have the same length.
* The two arrays are compatible in a dimension if they have the same size in the dimension or if one of the arrays has size 1 in that dimension.

In [ ]:
#Setting a value with index range (Broadcasting)
x[0:2]=100

#Show
x

### Slicing
 similar way to slicing a list - except you can do it in more than one dimension.

In [ ]:

slice = x[0:5]


slice

In [ ]:
#Change Slice
slice[:]=9

#Show Slice again
slice

Now note the changes also occur in our original array!

In [ ]:
x

## Indexing a 2D array

To access elements in this array, use two indices. One for the row and the other for the column. Note that both the column and the row indices start with 0. So if I need to access the value ‘10,’ use the index ‘3’ for the row and index ‘1’ for the column.

In [ ]:
array = np.arange(12).reshape(4,3)

array

In [ ]:
array[3][1]


In [ ]:
# 2D array slicing

#Shape (2,2) from top right corner
array[:2,1:]

In [ ]:
#Shape bottom row
array[2]

In [ ]:
#Shape bottom row
arr_2d[2,:]

## Selection

To select an element from Numpy Array , we can use [] operator

In [ ]:
w = np.arange(1, 20, 2)
w

In [ ]:
w > 5

In [ ]:
w[w>2]

In [ ]:
x = 5
w[w > x]